import type {
  AdminFormField,
  AdminModuleDefinition,
  AdminRecord,
  SelectOption,
} from '@/modules/admin/types';

const today = () => new Date().toISOString().slice(0, 10);
const currentYear = () => new Date().getFullYear();

const statusOptions = (...values: string[]): SelectOption[] =>
  values.map((value) => ({ label: value.replace(/_/g, ' '), value }));

const monthOptions = statusOptions(
  'january',
  'february',
  'march',
  'april',
  'may',
  'june',
  'july',
  'august',
  'september',
  'october',
  'november',
  'december',
);

const requiredId = (key: string, label: string): AdminFormField => ({
  key,
  label,
  required: true,
  placeholder: `${label} ID`,
  helper: 'Use the backend record ID from the related module.',
});

const statusFilter = (...values: string[]) => ({
  key: 'status',
  label: 'Status',
  type: 'select' as const,
  options: [{ label: 'All', value: '' }, ...statusOptions(...values)],
});

const withType =
  (type: 'exam' | 'test') =>
  (payload: AdminRecord): AdminRecord => ({
    ...payload,
    type,
  });

export const ADMIN_MODULES: AdminModuleDefinition[] = [
  {
    key: 'students',
    title: 'Students',
    subtitle: 'Profiles, guardians, enrollment and status',
    icon: 'graduation',
    listPath: '/students',
    getPath: '/students/:id',
    createPath: '/students',
    updatePath: '/students/:id',
    deletePath: '/students/:id',
    searchable: true,
    filters: [
      statusFilter('active', 'inactive', 'graduated', 'transferred'),
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
    ],
    clientSearchKeys: ['first_name', 'last_name', 'admission_no', 'guardian.name', 'guardian.phone'],
    displayFields: ['first_name', 'last_name', 'admission_no', 'class_name', 'class_id', 'status'],
    detailFields: [
      '_id',
      'admission_no',
      'first_name',
      'last_name',
      'class_id',
      'section',
      'guardian.name',
      'guardian.phone',
      'guardian.email',
      'status',
    ],
    fields: [
      { key: 'admission_no', label: 'Admission No' },
      { key: 'first_name', label: 'First Name', required: true },
      { key: 'last_name', label: 'Last Name', required: true },
      requiredId('class_id', 'Class'),
      { key: 'section', label: 'Section', required: true },
      { key: 'subjects', label: 'Subject IDs', type: 'csv', helper: 'Comma-separated subject IDs.' },
      { key: 'guardian.name', label: 'Guardian Name', required: true },
      { key: 'guardian.phone', label: 'Guardian Phone', required: true },
      { key: 'guardian.email', label: 'Guardian Email', type: 'email' },
      { key: 'email', label: 'Parent Account Email', type: 'email', createOnly: true },
      { key: 'password', label: 'Parent Account Password', type: 'password', createOnly: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        defaultValue: 'active',
        options: statusOptions('active', 'inactive', 'graduated', 'transferred'),
      },
    ],
  },
  {
    key: 'teachers',
    title: 'Teachers',
    subtitle: 'Faculty roster, credentials and class assignments',
    icon: 'users',
    listPath: '/teachers',
    getPath: '/teachers/:id',
    createPath: '/teachers',
    updatePath: '/teachers/:id',
    deletePath: '/teachers/:id',
    searchable: true,
    filters: [statusFilter('active', 'inactive', 'on_leave')],
    clientSearchKeys: ['first_name', 'last_name', 'email', 'phone', 'employee_no'],
    displayFields: ['first_name', 'last_name', 'employee_no', 'email', 'phone', 'status'],
    detailFields: [
      '_id',
      'employee_no',
      'first_name',
      'last_name',
      'email',
      'phone',
      'qualification',
      'subjects',
      'class_ids',
      'status',
    ],
    fields: [
      { key: 'first_name', label: 'First Name', required: true },
      { key: 'last_name', label: 'Last Name' },
      { key: 'email', label: 'Email', type: 'email', required: true, createOnly: true },
      { key: 'password', label: 'Password', type: 'password', createOnly: true },
      { key: 'phone', label: 'Phone', required: true },
      { key: 'qualification', label: 'Qualification' },
      { key: 'subjects', label: 'Subjects', type: 'csv', helper: 'Comma-separated subject names.' },
      { key: 'subject_ids', label: 'Subject IDs', type: 'csv' },
      { key: 'class_ids', label: 'Class IDs', type: 'csv' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        editOnly: true,
        options: statusOptions('active', 'inactive', 'on_leave'),
      },
    ],
  },
  {
    key: 'classes',
    title: 'Classes',
    subtitle: 'Sections, subject mapping and classroom capacity',
    icon: 'graduation',
    listPath: '/classes',
    getPath: '/classes/:id',
    createPath: '/classes',
    updatePath: '/classes/:id',
    deletePath: '/classes/:id',
    searchable: true,
    filters: [statusFilter('active', 'inactive', 'archived')],
    clientSearchKeys: ['name', 'section', 'code', 'room_number'],
    displayFields: ['name', 'section', 'code', 'student_count', 'class_teacher.name', 'status'],
    detailFields: [
      '_id',
      'name',
      'section',
      'code',
      'grade',
      'capacity',
      'passing_percentage',
      'class_teacher_id',
      'teacher_ids',
      'subject_ids',
      'room_number',
      'description',
      'status',
    ],
    fields: [
      { key: 'name', label: 'Class Name', required: true },
      { key: 'code', label: 'Code' },
      { key: 'grade', label: 'Grade' },
      { key: 'section', label: 'Section' },
      { key: 'capacity', label: 'Capacity', type: 'number' },
      { key: 'passing_percentage', label: 'Passing Percentage', type: 'number', defaultValue: 40 },
      { key: 'academic_year_id', label: 'Academic Year ID' },
      { key: 'class_teacher_id', label: 'Class Teacher ID' },
      { key: 'teacher_ids', label: 'Teacher IDs', type: 'csv' },
      { key: 'subject_ids', label: 'Subject IDs', type: 'csv' },
      { key: 'room_number', label: 'Room Number' },
      { key: 'description', label: 'Description', type: 'textarea' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        editOnly: true,
        options: statusOptions('active', 'inactive', 'archived'),
      },
    ],
  },
  {
    key: 'subjects',
    title: 'Subjects',
    subtitle: 'School subjects, marks and teacher ownership',
    icon: 'book',
    listPath: '/subjects',
    getPath: '/subjects/:id',
    createPath: '/subjects',
    updatePath: '/subjects/:id',
    updateMethod: 'PUT',
    deletePath: '/subjects/:id',
    searchable: true,
    filters: [statusFilter('active', 'inactive')],
    clientSearchKeys: ['name', 'code', 'teacher_name'],
    displayFields: ['name', 'code', 'teacher_name', 'total_marks', 'passing_marks', 'status'],
    detailFields: ['_id', 'name', 'code', 'description', 'teacher_id', 'teacher_name', 'total_marks', 'passing_marks', 'status'],
    fields: [
      { key: 'name', label: 'Subject Name', required: true },
      { key: 'code', label: 'Code' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'teacher_id', label: 'Teacher ID' },
      { key: 'total_marks', label: 'Total Marks', type: 'number' },
      { key: 'passing_marks', label: 'Passing Marks', type: 'number' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        defaultValue: 'active',
        options: statusOptions('active', 'inactive'),
      },
    ],
  },
  {
    key: 'academic-years',
    title: 'Academic Years',
    subtitle: 'Sessions, active year and date boundaries',
    icon: 'calendar',
    listPath: '/academic-years',
    getPath: '/academic-years/:id',
    createPath: '/academic-years',
    updatePath: '/academic-years/:id',
    deletePath: '/academic-years/:id',
    filters: [statusFilter('draft', 'active', 'completed', 'cancelled')],
    clientSearchKeys: ['year', 'description', 'status'],
    displayFields: ['year', 'start_date', 'end_date', 'is_active', 'status'],
    detailFields: ['_id', 'year', 'start_date', 'end_date', 'is_active', 'status', 'description'],
    fields: [
      { key: 'year', label: 'Year', required: true, placeholder: '2026-2027' },
      { key: 'start_date', label: 'Start Date', type: 'date', required: true, defaultValue: today() },
      { key: 'end_date', label: 'End Date', type: 'date', required: true },
      { key: 'is_active', label: 'Set Active', type: 'boolean', defaultValue: false },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'attendance',
    title: 'Attendance',
    subtitle: 'Daily student attendance records',
    icon: 'check-circle',
    listPath: '/attendance',
    getPath: '/attendance/:id',
    createPath: '/attendance',
    updatePath: '/attendance/:id',
    deletePath: '/attendance/:id',
    filters: [
      { key: 'date', label: 'Date', type: 'text', placeholder: 'YYYY-MM-DD' },
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
      { key: 'student_id', label: 'Student', type: 'text', placeholder: 'student_id' },
      statusFilter('present', 'absent'),
    ],
    clientSearchKeys: ['student_name', 'admission_no', 'class_name', 'status'],
    displayFields: ['student_name', 'admission_no', 'class_name', 'date', 'period', 'status'],
    detailFields: ['_id', 'student_id', 'student_name', 'class_id', 'class_name', 'date', 'period', 'status', 'note'],
    fields: [
      requiredId('student_id', 'Student'),
      requiredId('class_id', 'Class'),
      { key: 'date', label: 'Date', type: 'date', required: true, defaultValue: today() },
      { key: 'period', label: 'Period', type: 'number' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        defaultValue: 'present',
        options: statusOptions('present', 'absent'),
      },
      { key: 'note', label: 'Note', type: 'textarea' },
    ],
  },
  {
    key: 'attendance-sheet',
    title: 'Attendance Sheet',
    subtitle: 'Class attendance sheet from the backend join endpoint',
    icon: 'check-circle',
    listPath: '/attendance/sheet',
    filters: [
      { key: 'date', label: 'Date', type: 'text', placeholder: 'YYYY-MM-DD' },
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
    ],
    clientSearchKeys: ['student_name', 'admission_no', 'class_name', 'status'],
    displayFields: ['student_name', 'admission_no', 'class_name', 'status', 'date'],
    detailFields: ['student_id', 'student_name', 'admission_no', 'class_id', 'class_name', 'status', 'date', 'period'],
  },
  {
    key: 'exams',
    title: 'Exams',
    subtitle: 'Term exams, schedules and subject marks',
    icon: 'clipboard',
    listPath: '/exams',
    listParams: { type: 'exam' },
    getPath: '/exams/:id',
    createPath: '/exams',
    updatePath: '/exams/:id',
    deletePath: '/exams/:id',
    filters: [
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
      statusFilter('scheduled', 'completed', 'cancelled', 'results_published'),
    ],
    clientSearchKeys: ['title', 'term', 'subject', 'class_name', 'status'],
    displayFields: ['title', 'class_name', 'subject', 'starts_at', 'max_marks', 'status'],
    detailFields: ['_id', 'title', 'class_id', 'class_name', 'subject', 'subjects', 'term', 'starts_at', 'max_marks', 'status', 'description'],
    fields: [
      requiredId('class_id', 'Class'),
      { key: 'title', label: 'Title', required: true },
      { key: 'subject', label: 'Subject ID or Name', required: true },
      { key: 'max_marks', label: 'Max Marks', type: 'number', defaultValue: 100 },
      { key: 'term', label: 'Term' },
      { key: 'starts_at', label: 'Starts At', type: 'date', required: true, defaultValue: today() },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        defaultValue: 'scheduled',
        options: statusOptions('scheduled', 'completed', 'cancelled', 'results_published'),
      },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    transformPayload: withType('exam'),
  },
  {
    key: 'tests',
    title: 'Tests',
    subtitle: 'Class tests and quizzes',
    icon: 'clipboard',
    listPath: '/tests',
    listParams: { type: 'test' },
    getPath: '/tests/:id',
    createPath: '/tests',
    updatePath: '/tests/:id',
    deletePath: '/tests/:id',
    filters: [
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
      statusFilter('scheduled', 'completed', 'cancelled', 'results_published'),
    ],
    clientSearchKeys: ['title', 'subject', 'class_name', 'status'],
    displayFields: ['title', 'class_name', 'subject', 'starts_at', 'max_marks', 'status'],
    detailFields: ['_id', 'title', 'class_id', 'class_name', 'subject', 'starts_at', 'max_marks', 'status', 'description'],
    fields: [
      requiredId('class_id', 'Class'),
      { key: 'title', label: 'Title', required: true },
      { key: 'subject', label: 'Subject ID or Name', required: true },
      { key: 'max_marks', label: 'Max Marks', type: 'number', defaultValue: 20 },
      { key: 'starts_at', label: 'Starts At', type: 'date', required: true, defaultValue: today() },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        defaultValue: 'scheduled',
        options: statusOptions('scheduled', 'completed', 'cancelled', 'results_published'),
      },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    transformPayload: withType('test'),
  },
  {
    key: 'results',
    title: 'Results',
    subtitle: 'Marks entry and result records',
    icon: 'star',
    listPath: '/results',
    createPath: '/results',
    filters: [
      { key: 'exam_id', label: 'Exam', type: 'text', placeholder: 'exam_id' },
      { key: 'student_id', label: 'Student', type: 'text', placeholder: 'student_id' },
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
    ],
    clientSearchKeys: ['student_name', 'admission_no', 'exam_title', 'class_name', 'grade'],
    displayFields: ['student_name', 'exam_title', 'obtained_marks', 'max_marks', 'percentage', 'grade'],
    detailFields: ['_id', 'exam_id', 'exam_title', 'student_id', 'student_name', 'obtained_marks', 'max_marks', 'percentage', 'grade', 'remarks'],
    fields: [
      requiredId('exam_id', 'Exam'),
      requiredId('student_id', 'Student'),
      { key: 'obtained_marks', label: 'Obtained Marks', type: 'number', required: true },
      { key: 'remarks', label: 'Remarks', type: 'textarea' },
    ],
  },
  {
    key: 'homework',
    title: 'Homework',
    subtitle: 'Assignments, due dates and submissions',
    icon: 'book',
    listPath: '/homework',
    getPath: '/homework/:id',
    createPath: '/homework',
    updatePath: '/homework/:id',
    deletePath: '/homework/:id',
    filters: [
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
      statusFilter('draft', 'assigned', 'closed', 'archived'),
    ],
    clientSearchKeys: ['title', 'class_name', 'teacher_name', 'subject_name', 'status'],
    displayFields: ['title', 'class_name', 'subject_name', 'due_at', 'status'],
    detailFields: ['_id', 'title', 'class_id', 'class_name', 'subject_id', 'subject_name', 'teacher_id', 'teacher_name', 'due_at', 'status', 'visibility', 'instructions'],
    fields: [
      requiredId('class_id', 'Class'),
      { key: 'section', label: 'Section' },
      { key: 'teacher_id', label: 'Teacher ID' },
      { key: 'subject_id', label: 'Subject ID or Name' },
      { key: 'title', label: 'Title', required: true },
      { key: 'instructions', label: 'Instructions', type: 'textarea' },
      { key: 'due_at', label: 'Due Date', type: 'date', required: true, defaultValue: today() },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        defaultValue: 'assigned',
        options: statusOptions('draft', 'assigned', 'closed', 'archived'),
      },
      { key: 'visibility', label: 'Visibility', type: 'select', defaultValue: 'class', options: statusOptions('class', 'students') },
      { key: 'attachments', label: 'Attachments', type: 'csv' },
    ],
  },
  {
    key: 'behavior',
    title: 'Behavior',
    subtitle: 'Discipline, incidents and follow-up status',
    icon: 'shield',
    listPath: '/behavior',
    getPath: '/behavior/:id',
    createPath: '/behavior',
    updatePath: '/behavior/:id',
    deletePath: '/behavior/:id',
    filters: [
      { key: 'student_id', label: 'Student', type: 'text', placeholder: 'student_id' },
      statusFilter('open', 'reviewing', 'resolved', 'escalated', 'dismissed'),
    ],
    clientSearchKeys: ['student_name', 'class_name', 'category', 'severity', 'status'],
    displayFields: ['student_name', 'class_name', 'category', 'severity', 'status'],
    detailFields: ['_id', 'student_id', 'student_name', 'class_id', 'class_name', 'category', 'incident_type', 'description', 'severity', 'action_taken', 'status', 'warning_count', 'parent_notified', 'notes'],
    fields: [
      requiredId('student_id', 'Student'),
      requiredId('class_id', 'Class'),
      { key: 'category', label: 'Category', defaultValue: 'conduct' },
      { key: 'incident_type', label: 'Incident Type' },
      { key: 'description', label: 'Description', type: 'textarea', required: true },
      {
        key: 'severity',
        label: 'Severity',
        type: 'select',
        required: true,
        defaultValue: 'low',
        options: statusOptions('low', 'medium', 'critical', 'minor', 'moderate', 'major'),
      },
      { key: 'action_taken', label: 'Action Taken', type: 'textarea' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        defaultValue: 'open',
        options: statusOptions('open', 'reviewing', 'resolved', 'escalated', 'dismissed'),
      },
      { key: 'warning_count', label: 'Warning Count', type: 'number' },
      { key: 'parent_notified', label: 'Parent Notified', type: 'boolean' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
      { key: 'attachments', label: 'Attachments', type: 'csv' },
    ],
  },
  {
    key: 'leave',
    title: 'Leave',
    subtitle: 'Student and teacher leave requests',
    icon: 'clock',
    listPath: '/leave',
    getPath: '/leave/:id',
    createPath: '/leave',
    updatePath: '/leave/:id',
    deletePath: '/leave/:id',
    filters: [
      { key: 'requester_type', label: 'Requester', type: 'select', options: [{ label: 'All', value: '' }, ...statusOptions('student', 'teacher')] },
      statusFilter('pending', 'approved', 'rejected', 'cancelled'),
    ],
    clientSearchKeys: ['requester_name', 'class_name', 'leave_type', 'status', 'reason'],
    displayFields: ['requester_name', 'requester_type', 'leave_type', 'start_date', 'end_date', 'status'],
    detailFields: ['_id', 'requester_type', 'requester_id', 'requester_name', 'class_name', 'leave_type', 'start_date', 'end_date', 'reason', 'status', 'rejection_reason'],
    fields: [
      {
        key: 'requester_type',
        label: 'Requester Type',
        type: 'select',
        required: true,
        defaultValue: 'teacher',
        options: statusOptions('student', 'teacher'),
      },
      requiredId('requester_id', 'Requester'),
      { key: 'requester_name', label: 'Requester Name' },
      {
        key: 'leave_type',
        label: 'Leave Type',
        type: 'select',
        required: true,
        defaultValue: 'sick',
        options: statusOptions('sick', 'personal', 'family', 'vacation', 'other'),
      },
      { key: 'start_date', label: 'Start Date', type: 'date', required: true, defaultValue: today() },
      { key: 'end_date', label: 'End Date', type: 'date', required: true, defaultValue: today() },
      { key: 'reason', label: 'Reason', type: 'textarea', required: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        editOnly: true,
        options: statusOptions('pending', 'approved', 'rejected', 'cancelled'),
      },
      { key: 'rejection_reason', label: 'Rejection Reason', type: 'textarea', editOnly: true },
    ],
    rowActions: [
      {
        key: 'approve',
        label: 'Approve',
        method: 'PATCH',
        path: (record) => `/leave/${recordId(record)}`,
        body: () => ({ status: 'approved' }),
        confirm: 'Approve this leave request?',
      },
      {
        key: 'reject',
        label: 'Reject',
        method: 'PATCH',
        path: (record) => `/leave/${recordId(record)}`,
        body: () => ({ status: 'rejected' }),
        confirm: 'Reject this leave request?',
        destructive: true,
      },
    ],
  },
  {
    key: 'events',
    title: 'Events',
    subtitle: 'Calendar events, holidays and activities',
    icon: 'calendar',
    listPath: '/events',
    getPath: '/events/:id',
    createPath: '/events',
    updatePath: '/events/:id',
    deletePath: '/events/:id',
    filters: [
      { key: 'event_type', label: 'Type', type: 'select', options: [{ label: 'All', value: '' }, ...statusOptions('academic', 'holiday', 'sports', 'cultural', 'other')] },
      statusFilter('scheduled', 'cancelled', 'completed'),
    ],
    clientSearchKeys: ['title', 'description', 'event_type', 'location', 'status'],
    displayFields: ['title', 'event_type', 'start_date', 'end_date', 'location', 'status'],
    detailFields: ['_id', 'title', 'description', 'event_type', 'start_date', 'end_date', 'start_time', 'end_time', 'location', 'visibility', 'target_class_ids', 'organizer', 'status'],
    fields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      {
        key: 'event_type',
        label: 'Event Type',
        type: 'select',
        defaultValue: 'academic',
        options: statusOptions('academic', 'holiday', 'sports', 'cultural', 'other'),
      },
      { key: 'start_date', label: 'Start Date', type: 'date', required: true, defaultValue: today() },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'start_time', label: 'Start Time', type: 'time' },
      { key: 'end_time', label: 'End Time', type: 'time' },
      { key: 'location', label: 'Location' },
      {
        key: 'visibility',
        label: 'Visibility',
        type: 'select',
        defaultValue: 'all',
        options: statusOptions('all', 'specific_classes'),
      },
      { key: 'target_class_ids', label: 'Target Class IDs', type: 'csv' },
      { key: 'organizer', label: 'Organizer' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        defaultValue: 'scheduled',
        options: statusOptions('scheduled', 'cancelled', 'completed'),
      },
    ],
  },
  {
    key: 'announcements',
    title: 'Announcements',
    subtitle: 'School-wide and audience-targeted broadcasts',
    icon: 'megaphone',
    listPath: '/announcements',
    getPath: '/announcements/:id',
    createPath: '/announcements',
    updatePath: '/announcements/:id',
    deletePath: '/announcements/:id',
    filters: [{ key: 'audience', label: 'Audience', type: 'text', placeholder: 'all, teachers, students' }],
    clientSearchKeys: ['title', 'body', 'content', 'audience', 'priority'],
    displayFields: ['title', 'audience', 'priority', 'created_at'],
    detailFields: ['_id', 'title', 'body', 'content', 'audience', 'priority', 'created_at'],
    fields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'body', label: 'Body', type: 'textarea' },
      { key: 'audience', label: 'Audience', defaultValue: 'all' },
      {
        key: 'priority',
        label: 'Priority',
        type: 'select',
        defaultValue: 'normal',
        options: statusOptions('low', 'normal', 'high', 'urgent'),
      },
    ],
  },
  {
    key: 'timetable',
    title: 'Timetable',
    subtitle: 'Weekly class periods and teacher allocation',
    icon: 'calendar',
    listPath: '/timetable',
    getPath: '/timetable/:id',
    createPath: '/timetable',
    updatePath: '/timetable/:id',
    deletePath: '/timetable/:id',
    filters: [
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
      { key: 'teacher_id', label: 'Teacher', type: 'text', placeholder: 'teacher_id' },
      { key: 'day_of_week', label: 'Day', type: 'select', options: [{ label: 'All', value: '' }, ...statusOptions('1', '2', '3', '4', '5', '6', '7')] },
    ],
    clientSearchKeys: ['class_name', 'teacher_name', 'subject_name', 'room'],
    displayFields: ['class_name', 'subject_name', 'teacher_name', 'day_of_week', 'period_number', 'start_time', 'end_time'],
    detailFields: ['_id', 'class_id', 'class_name', 'subject_id', 'subject_name', 'teacher_id', 'teacher_name', 'day_of_week', 'period_number', 'start_time', 'end_time', 'room'],
    fields: [
      requiredId('class_id', 'Class'),
      requiredId('subject_id', 'Subject'),
      requiredId('teacher_id', 'Teacher'),
      { key: 'day_of_week', label: 'Day of Week', type: 'number', required: true, defaultValue: 1 },
      { key: 'period_number', label: 'Period Number', type: 'number', required: true, defaultValue: 1 },
      { key: 'start_time', label: 'Start Time', type: 'time', required: true, defaultValue: '08:00' },
      { key: 'end_time', label: 'End Time', type: 'time', required: true, defaultValue: '09:00' },
      { key: 'room', label: 'Room' },
    ],
  },
  {
    key: 'live-classes',
    title: 'Live Classes',
    subtitle: 'Jitsi sessions and live learning links',
    icon: 'video',
    listPath: '/live/classes',
    getPath: '/live/classes/:id',
    createPath: '/live/classes/schedule',
    updatePath: '/live/classes/:id',
    deletePath: '/live/classes/:id',
    filters: [
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
      statusFilter('scheduled', 'live', 'completed', 'cancelled'),
    ],
    clientSearchKeys: ['title', 'class_name', 'subject', 'status'],
    displayFields: ['title', 'class_name', 'subject', 'starts_at', 'ends_at', 'status'],
    detailFields: ['_id', 'title', 'class_id', 'class_name', 'subject', 'description', 'starts_at', 'ends_at', 'host_teacher_id', 'audience_type', 'target_student_id', 'join_url', 'status'],
    fields: [
      requiredId('class_id', 'Class'),
      { key: 'subject', label: 'Subject' },
      { key: 'title', label: 'Title', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'starts_at', label: 'Starts At', type: 'date', required: true, defaultValue: today() },
      { key: 'ends_at', label: 'Ends At', type: 'date', required: true, defaultValue: today() },
      { key: 'host_teacher_id', label: 'Host Teacher ID' },
      { key: 'audience_type', label: 'Audience Type', type: 'select', defaultValue: 'CLASS', options: statusOptions('CLASS', 'STUDENT') },
      { key: 'target_student_id', label: 'Target Student ID' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        editOnly: true,
        options: statusOptions('scheduled', 'live', 'completed', 'cancelled'),
      },
    ],
  },
  {
    key: 'certificate-templates',
    title: 'Certificate Templates',
    subtitle: 'Template CRUD for generated certificates',
    icon: 'star',
    listPath: '/certificates/templates',
    getPath: '/certificates/templates/:id',
    createPath: '/certificates/templates',
    updatePath: '/certificates/templates/:id',
    deletePath: '/certificates/templates/:id',
    clientSearchKeys: ['name', 'type', 'orientation'],
    displayFields: ['name', 'type', 'orientation', 'is_default', 'status'],
    detailFields: ['_id', 'name', 'type', 'orientation', 'background_url', 'watermark_url', 'border_style', 'body_text', 'is_default', 'status'],
    fields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'type', label: 'Type', defaultValue: 'character' },
      { key: 'orientation', label: 'Orientation', type: 'select', defaultValue: 'landscape', options: statusOptions('landscape', 'portrait') },
      { key: 'background_url', label: 'Background URL' },
      { key: 'watermark_url', label: 'Watermark URL' },
      { key: 'border_style', label: 'Border Style' },
      { key: 'body_text', label: 'Body Text', type: 'textarea' },
      { key: 'is_default', label: 'Default Template', type: 'boolean' },
      { key: 'elements', label: 'Elements JSON', type: 'json', defaultValue: [] },
    ],
    rowActions: [
      {
        key: 'duplicate',
        label: 'Duplicate',
        method: 'POST',
        path: (record) => `/certificates/templates/${recordId(record)}/duplicate`,
        confirm: 'Duplicate this template?',
      },
    ],
  },
  {
    key: 'certificates',
    title: 'Certificates',
    subtitle: 'Generated certificates and revocation',
    icon: 'star',
    listPath: '/certificates',
    createPath: '/certificates/generate',
    filters: [
      { key: 'student_id', label: 'Student', type: 'text', placeholder: 'student_id' },
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
      { key: 'type', label: 'Type', type: 'text', placeholder: 'type' },
    ],
    clientSearchKeys: ['student_name', 'class_name', 'type', 'status', 'verification_code'],
    displayFields: ['student_name', 'class_name', 'type', 'issue_date', 'status'],
    detailFields: ['_id', 'student_id', 'student_name', 'class_id', 'class_name', 'type', 'issue_date', 'verification_code', 'status'],
    fields: [
      requiredId('template_id', 'Template'),
      { key: 'student_ids', label: 'Student IDs', type: 'csv', required: true, helper: 'Comma-separated student IDs.' },
      { key: 'issue_date', label: 'Issue Date', type: 'date', defaultValue: today() },
    ],
    rowActions: [
      {
        key: 'revoke',
        label: 'Revoke',
        method: 'POST',
        path: (record) => `/certificates/${recordId(record)}/revoke`,
        confirm: 'Revoke this certificate?',
        destructive: true,
      },
    ],
  },
  {
    key: 'question-bank',
    title: 'Question Bank',
    subtitle: 'Internal question repository, moderation and starring',
    icon: 'book',
    listPath: '/question-bank',
    createPath: '/question-bank',
    deletePath: '/questions/:id',
    searchable: true,
    filters: [
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
      { key: 'subject_id', label: 'Subject', type: 'text', placeholder: 'subject_id' },
      { key: 'status', label: 'Status', type: 'select', options: [{ label: 'All', value: '' }, ...statusOptions('draft', 'approved', 'rejected', 'archived')] },
      { key: 'difficulty', label: 'Difficulty', type: 'select', options: [{ label: 'All', value: '' }, ...statusOptions('easy', 'medium', 'hard')] },
    ],
    clientSearchKeys: ['question', 'question_html', 'class_name', 'subject_name', 'chapter_name', 'type', 'status'],
    displayFields: ['question', 'class_name', 'subject_name', 'chapter_name', 'difficulty', 'status'],
    detailFields: ['_id', 'question', 'question_html', 'class_id', 'class_name', 'subject_id', 'subject_name', 'chapter_id', 'chapter_name', 'type', 'difficulty', 'answer', 'marks', 'status'],
    fields: [
      requiredId('class_id', 'Class'),
      { key: 'class_name', label: 'Class Name' },
      { key: 'subject_id', label: 'Subject ID' },
      { key: 'subject_name', label: 'Subject Name' },
      { key: 'chapter_id', label: 'Chapter ID' },
      { key: 'chapter_name', label: 'Chapter Name' },
      { key: 'type', label: 'Type', defaultValue: 'question_answers' },
      { key: 'difficulty', label: 'Difficulty', type: 'select', defaultValue: 'medium', options: statusOptions('easy', 'medium', 'hard') },
      { key: 'question', label: 'Question', type: 'textarea', required: true },
      { key: 'options', label: 'Options JSON', type: 'json' },
      { key: 'answer', label: 'Answer', type: 'textarea' },
      { key: 'marks', label: 'Marks', type: 'number', defaultValue: 1 },
    ],
    rowActions: [
      {
        key: 'archive',
        label: 'Archive',
        method: 'POST',
        path: (record) => `/question-bank/${recordId(record)}/archive`,
        destructive: true,
      },
      {
        key: 'restore',
        label: 'Restore',
        method: 'POST',
        path: (record) => `/question-bank/${recordId(record)}/restore`,
      },
      {
        key: 'star',
        label: 'Star',
        method: 'POST',
        path: (record) => `/question-bank/${recordId(record)}/star`,
      },
    ],
  },
  {
    key: 'question-papers',
    title: 'Question Papers',
    subtitle: 'Saved papers and generated assessments',
    icon: 'clipboard',
    listPath: '/question-papers',
    getPath: '/question-papers/:id',
    createPath: '/question-papers',
    deletePath: '/question-papers/:id',
    searchable: true,
    clientSearchKeys: ['title', 'class_name', 'subject_name', 'teacher_name', 'status'],
    displayFields: ['title', 'class_name', 'subject_name', 'date', 'status'],
    detailFields: ['_id', 'title', 'class_id', 'class_name', 'subject_id', 'subject_name', 'teacher_id', 'teacher_name', 'chapter_ids', 'date', 'status'],
    fields: [
      { key: 'title', label: 'Title', required: true },
      requiredId('class_id', 'Class'),
      { key: 'class_name', label: 'Class Name' },
      { key: 'subject_id', label: 'Subject ID' },
      { key: 'subject_name', label: 'Subject Name' },
      { key: 'chapter_ids', label: 'Chapter IDs', type: 'csv' },
      { key: 'teacher_id', label: 'Teacher ID' },
      { key: 'date', label: 'Date', type: 'date', defaultValue: today() },
      { key: 'questions', label: 'Questions JSON', type: 'json', defaultValue: [] },
    ],
  },
  {
    key: 'chapters',
    title: 'Chapters',
    subtitle: 'Chapter catalog used by the question generator',
    icon: 'book',
    listPath: '/chapters',
    createPath: '/chapters',
    filters: [
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
      { key: 'subject_id', label: 'Subject', type: 'text', placeholder: 'subject_id' },
      statusFilter('active', 'archived'),
    ],
    clientSearchKeys: ['title', 'subject_name', 'class_name', 'status'],
    displayFields: ['chapter_number', 'title', 'class_name', 'subject_name', 'status'],
    detailFields: ['_id', 'class_id', 'class_name', 'subject_id', 'subject_name', 'chapter_number', 'title', 'status'],
    fields: [
      requiredId('class_id', 'Class'),
      { key: 'subject_id', label: 'Subject ID' },
      { key: 'title', label: 'Title', required: true },
      { key: 'chapter_number', label: 'Chapter Number', type: 'number' },
    ],
    rowActions: [
      {
        key: 'archive',
        label: 'Archive',
        method: 'POST',
        path: (record) => `/chapters/${recordId(record)}/archive`,
        destructive: true,
      },
    ],
  },
  {
    key: 'class-fees',
    title: 'Class Fee Components',
    subtitle: 'Per-class fee setup, toggles and duplicate/delete actions',
    icon: 'wallet',
    listPath: '/classes/:class_id/fees/components',
    requiredFilters: ['class_id'],
    filters: [{ key: 'class_id', label: 'Class', type: 'text', placeholder: 'Required class_id' }],
    createPath: '/classes/:class_id/fees/components',
    updatePath: '/classes/:class_id/fees/components/:id',
    deletePath: '/classes/:class_id/fees/components/:id',
    clientSearchKeys: ['fee_type', 'fee_type_id', 'type', 'status', 'notes'],
    displayFields: ['fee_type', 'amount', 'type', 'recurring_cycle', 'status'],
    detailFields: ['_id', 'class_id', 'fee_type_id', 'fee_type', 'amount', 'type', 'recurring_cycle', 'due_month', 'due_year', 'notes', 'status'],
    fields: [
      requiredId('class_id', 'Class'),
      { key: 'fee_type_id', label: 'Fee Type ID' },
      { key: 'name', label: 'Fee Type Name', helper: 'Used when Fee Type ID is empty.' },
      { key: 'amount', label: 'Amount', type: 'number', required: true },
      { key: 'type', label: 'Type', type: 'select', defaultValue: 'recurring', options: statusOptions('recurring', 'onetime') },
      { key: 'recurring_cycle', label: 'Recurring Cycle', defaultValue: 'monthly' },
      { key: 'due_month', label: 'Due Month', type: 'select', options: monthOptions },
      { key: 'due_year', label: 'Due Year', type: 'number', defaultValue: currentYear() },
      { key: 'notes', label: 'Notes', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', defaultValue: 'active', options: statusOptions('active', 'inactive') },
    ],
    rowActions: [
      {
        key: 'toggle',
        label: 'Toggle',
        method: 'POST',
        path: (record) => `/classes/${record.class_id}/fees/components/${recordId(record)}/toggle`,
      },
      {
        key: 'duplicate',
        label: 'Duplicate',
        method: 'POST',
        path: (record) => `/classes/${record.class_id}/fees/components/${recordId(record)}/duplicate`,
      },
    ],
  },
  {
    key: 'fee-types',
    title: 'Fee Types',
    subtitle: 'Reusable school fee categories',
    icon: 'wallet',
    listPath: '/fees/types',
    createPath: '/fees/types',
    clientSearchKeys: ['name', 'description', 'status'],
    displayFields: ['name', 'amount', 'frequency', 'status'],
    detailFields: ['_id', 'name', 'description', 'amount', 'frequency', 'status'],
    fields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'amount', label: 'Amount', type: 'number' },
      { key: 'frequency', label: 'Frequency', defaultValue: 'monthly' },
      { key: 'status', label: 'Status', type: 'select', defaultValue: 'active', options: statusOptions('active', 'inactive') },
    ],
  },
  {
    key: 'fees',
    title: 'Fees',
    subtitle: 'Monthly vouchers, payments and ledger state',
    icon: 'wallet',
    listPath: '/fees',
    createPath: '/fees/generate',
    filters: [
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
      { key: 'student_id', label: 'Student', type: 'text', placeholder: 'student_id' },
      { key: 'month', label: 'Month', type: 'select', options: [{ label: 'All', value: '' }, ...monthOptions] },
      { key: 'status', label: 'Status', type: 'select', options: [{ label: 'All', value: '' }, ...statusOptions('unpaid', 'paid', 'partial', 'overdue', 'void')] },
    ],
    clientSearchKeys: ['student_name', 'class_name', 'month', 'status'],
    displayFields: ['student_name', 'class_name', 'month', 'year', 'effective_amount', 'paid_amount', 'status'],
    detailFields: ['_id', 'invoice_no', 'student_id', 'student_name', 'class_id', 'class_name', 'month', 'year', 'amount', 'effective_amount', 'paid_amount', 'outstanding_amount', 'due_at', 'status'],
    fields: [
      requiredId('class_id', 'Class'),
      { key: 'month', label: 'Month', type: 'select', required: true, options: monthOptions },
      { key: 'year', label: 'Year', type: 'number', required: true, defaultValue: currentYear() },
      { key: 'student_ids', label: 'Student IDs', type: 'csv', helper: 'Optional comma-separated subset.' },
    ],
  },
  {
    key: 'fee-ledger',
    title: 'Fee Ledger',
    subtitle: 'Ledger dashboard with status, class, month and search filters',
    icon: 'wallet',
    listPath: '/fees/ledger',
    searchable: true,
    filters: [
      { key: 'class_id', label: 'Class', type: 'text', placeholder: 'class_id' },
      { key: 'month', label: 'Month', type: 'select', options: [{ label: 'All', value: '' }, ...monthOptions] },
      { key: 'year', label: 'Year', type: 'text', placeholder: String(currentYear()) },
      { key: 'status', label: 'Status', type: 'select', options: [{ label: 'All', value: '' }, ...statusOptions('paid', 'partial', 'unpaid')] },
    ],
    clientSearchKeys: ['student.name', 'student_name', 'admission_no', 'status'],
    displayFields: ['student.name', 'student_name', 'current_fee', 'paid_total', 'remaining', 'status'],
    detailFields: ['student.id', 'student.name', 'student.admission_no', 'current_fee', 'carry_forward', 'total_payable', 'paid_total', 'remaining', 'status'],
  },
  {
    key: 'fee-dashboard',
    title: 'Fee Dashboard',
    subtitle: 'Collection totals, pending amounts and collection rate',
    icon: 'wallet',
    listPath: '/school/fees/dashboard-stats',
    singleton: true,
    displayFields: ['total_collected', 'total_pending', 'collection_rate', 'pending_count'],
    detailFields: ['total_collected', 'total_pending', 'collection_rate', 'pending_count'],
  },
  {
    key: 'fee-classes-summary',
    title: 'Fee Classes Summary',
    subtitle: 'Class-level collection totals and invoice counts',
    icon: 'wallet',
    listPath: '/school/fees/classes-summary',
    clientSearchKeys: ['name', 'section'],
    displayFields: ['name', 'section', 'student_count', 'invoice_count', 'collected', 'pending'],
    detailFields: ['_id', 'name', 'section', 'student_count', 'invoice_count', 'total', 'collected', 'pending'],
  },
  {
    key: 'fee-payments',
    title: 'Fee Payments',
    subtitle: 'Payment history and payment recording',
    icon: 'wallet',
    listPath: '/fees/payments',
    createPath: '/fees/:fee_id/pay',
    filters: [
      { key: 'student_id', label: 'Student', type: 'text', placeholder: 'student_id' },
      { key: 'payment_method', label: 'Method', type: 'select', options: [{ label: 'All', value: '' }, ...statusOptions('cash', 'bank', 'card', 'wallet', 'other')] },
      { key: 'from', label: 'From', type: 'text', placeholder: 'YYYY-MM-DD' },
      { key: 'to', label: 'To', type: 'text', placeholder: 'YYYY-MM-DD' },
    ],
    clientSearchKeys: ['student_id', 'receipt_no', 'payment_method', 'reference_no'],
    displayFields: ['receipt_no', 'student_id', 'amount', 'payment_method', 'payment_date'],
    detailFields: ['_id', 'fee_id', 'student_id', 'amount', 'payment_method', 'reference_no', 'receipt_no', 'payment_date', 'notes'],
    fields: [
      requiredId('fee_id', 'Fee Invoice'),
      requiredId('student_id', 'Student'),
      { key: 'amount', label: 'Amount', type: 'number', required: true },
      { key: 'payment_method', label: 'Payment Method', type: 'select', required: true, defaultValue: 'cash', options: statusOptions('cash', 'bank', 'card', 'wallet', 'other') },
      { key: 'reference_no', label: 'Reference No' },
      { key: 'payment_date', label: 'Payment Date', type: 'date', defaultValue: today() },
      { key: 'notes', label: 'Notes', type: 'textarea' },
      { key: 'use_credit', label: 'Use Wallet Credit', type: 'boolean' },
      { key: 'credit_amount', label: 'Credit Amount', type: 'number' },
    ],
  },
  {
    key: 'fee-daily-collection',
    title: 'Daily Fee Collection',
    subtitle: 'Cash and non-cash collection for a day',
    icon: 'wallet',
    listPath: '/fees/daily-collection',
    filters: [{ key: 'date', label: 'Date', type: 'text', placeholder: 'YYYY-MM-DD' }],
    clientSearchKeys: ['student_id', 'receipt_no', 'payment_method'],
    displayFields: ['receipt_no', 'student_id', 'amount', 'payment_method', 'payment_date'],
    detailFields: ['_id', 'fee_id', 'student_id', 'amount', 'payment_method', 'receipt_no', 'payment_date', 'notes'],
  },
  {
    key: 'fee-adjustments',
    title: 'Fee Adjustments',
    subtitle: 'Student fee penalties, discounts and waivers',
    icon: 'wallet',
    listPath: '/fees/adjustments',
    createPath: '/fees/adjustments',
    deletePath: '/fees/adjustments/:id',
    filters: [{ key: 'student_id', label: 'Student', type: 'text', placeholder: 'student_id' }],
    clientSearchKeys: ['student_id', 'type', 'reason', 'status'],
    displayFields: ['student_id', 'type', 'amount', 'valid_from', 'valid_until', 'status'],
    detailFields: ['_id', 'student_id', 'type', 'amount', 'reason', 'valid_from', 'valid_until', 'status'],
    fields: [
      requiredId('student_id', 'Student'),
      { key: 'type', label: 'Type', type: 'select', required: true, options: statusOptions('penalty', 'discount', 'waiver') },
      { key: 'amount', label: 'Amount', type: 'number', required: true },
      { key: 'reason', label: 'Reason', required: true },
      { key: 'valid_from', label: 'Valid From', type: 'date', required: true, defaultValue: today() },
      { key: 'valid_until', label: 'Valid Until', type: 'date', required: true, defaultValue: today() },
    ],
  },
  {
    key: 'fee-discounts',
    title: 'Fee Discounts',
    subtitle: 'Student discounts for current or recurring invoices',
    icon: 'wallet',
    listPath: '/fee-discounts',
    createPath: '/fee-discounts',
    deletePath: '/fee-discounts/:id',
    filters: [{ key: 'student_id', label: 'Student', type: 'text', placeholder: 'student_id' }],
    clientSearchKeys: ['student_id', 'fee_id', 'type', 'apply_mode', 'month'],
    displayFields: ['student_id', 'type', 'value', 'apply_mode', 'month', 'year'],
    detailFields: ['_id', 'student_id', 'fee_id', 'type', 'value', 'apply_mode', 'month', 'year', 'notes'],
    fields: [
      requiredId('student_id', 'Student'),
      { key: 'fee_id', label: 'Fee ID' },
      { key: 'type', label: 'Type', type: 'select', required: true, defaultValue: 'percentage', options: statusOptions('percentage', 'fixed') },
      { key: 'value', label: 'Value', type: 'number', required: true },
      { key: 'apply_mode', label: 'Apply Mode', type: 'select', required: true, defaultValue: 'this_month', options: statusOptions('this_month', 'recurring') },
      { key: 'month', label: 'Month', type: 'select', options: monthOptions },
      { key: 'year', label: 'Year', type: 'number', defaultValue: currentYear() },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'scholarships',
    title: 'Scholarships',
    subtitle: 'Student scholarship settings',
    icon: 'wallet',
    listPath: '/scholarships',
    createPath: '/scholarships',
    singleton: true,
    filters: [{ key: 'student_id', label: 'Student', type: 'text', placeholder: 'student_id' }],
    requiredFilters: ['student_id'],
    displayFields: ['student_id', 'enabled', 'type', 'value'],
    detailFields: ['_id', 'student_id', 'enabled', 'type', 'value', 'apply_monthly', 'apply_fine', 'apply_onetime', 'start_date', 'end_date', 'notes'],
    fields: [
      requiredId('student_id', 'Student'),
      { key: 'enabled', label: 'Enabled', type: 'boolean', defaultValue: true },
      { key: 'type', label: 'Type', type: 'select', defaultValue: 'percentage', options: statusOptions('percentage', 'fixed') },
      { key: 'value', label: 'Value', type: 'number', required: true },
      { key: 'apply_monthly', label: 'Apply Monthly', type: 'boolean', defaultValue: true },
      { key: 'apply_fine', label: 'Apply Fine', type: 'boolean' },
      { key: 'apply_onetime', label: 'Apply One-Time', type: 'boolean' },
      { key: 'year', label: 'Year', type: 'number', defaultValue: currentYear() },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'wallet',
    title: 'Student Wallet',
    subtitle: 'Wallet credit balance for a student',
    icon: 'wallet',
    listPath: '/wallet',
    singleton: true,
    filters: [{ key: 'student_id', label: 'Student', type: 'text', placeholder: 'Required student_id' }],
    requiredFilters: ['student_id'],
    displayFields: ['student_id', 'balance', 'currency'],
    detailFields: ['student_id', 'balance', 'currency', 'updated_at'],
  },
  {
    key: 'wallet-transactions',
    title: 'Wallet Transactions',
    subtitle: 'Student wallet transaction history',
    icon: 'wallet',
    listPath: '/wallet/transactions',
    filters: [{ key: 'student_id', label: 'Student', type: 'text', placeholder: 'Required student_id' }],
    requiredFilters: ['student_id'],
    clientSearchKeys: ['type', 'reference_no', 'description'],
    displayFields: ['type', 'amount', 'balance_after', 'created_at'],
    detailFields: ['_id', 'student_id', 'type', 'amount', 'balance_after', 'reference_no', 'description', 'created_at'],
  },
  {
    key: 'payment-methods',
    title: 'Payment Methods',
    subtitle: 'Configured payment methods for school billing',
    icon: 'wallet',
    listPath: '/payment/methods',
    clientSearchKeys: ['name', 'type', 'status'],
    displayFields: ['name', 'type', 'account_title', 'status'],
    detailFields: ['_id', 'name', 'type', 'account_title', 'account_number', 'instructions', 'status'],
  },
  {
    key: 'subscription',
    title: 'Subscription',
    subtitle: 'Plan, student limit and package access',
    icon: 'wallet',
    listPath: '/subscription/current',
    singleton: true,
    displayFields: ['subscription.plan_name', 'students_used', 'students_limit', 'days_remaining', 'is_expired'],
    detailFields: ['subscription.plan_name', 'subscription.status', 'students_used', 'students_limit', 'days_remaining', 'can_trial', 'selected_packages', 'allowed_modules'],
    rowActions: [
      {
        key: 'trial',
        label: 'Start Trial',
        method: 'POST',
        path: () => '/subscription/start-trial',
        confirm: 'Start the available trial for this school?',
      },
    ],
  },
  {
    key: 'subscription-plans',
    title: 'Subscription Plans',
    subtitle: 'Available plans from the subscription catalog',
    icon: 'wallet',
    listPath: '/subscription/plans',
    clientSearchKeys: ['name', 'plan_name', 'status'],
    displayFields: ['name', 'plan_name', 'student_limit', 'amount', 'duration_days'],
    detailFields: ['_id', 'id', 'name', 'plan_name', 'student_limit', 'amount', 'duration_days', 'features', 'status'],
  },
  {
    key: 'subscription-history',
    title: 'Subscription History',
    subtitle: 'Plan changes, renewals and payment state',
    icon: 'wallet',
    listPath: '/subscription/history',
    clientSearchKeys: ['plan_name', 'action', 'payment_status'],
    displayFields: ['plan_name', 'action', 'amount', 'payment_status', 'created_at'],
    detailFields: ['_id', 'plan_name', 'student_limit', 'amount', 'payment_status', 'action', 'start_date', 'end_date', 'created_at'],
  },
  {
    key: 'domain-status',
    title: 'Domain Status',
    subtitle: 'Connected domain state reported by the backend',
    icon: 'settings',
    listPath: '/domain/status',
    singleton: true,
    displayFields: ['status', 'domain'],
    detailFields: ['status', 'domain', 'target', 'verified_at'],
  },
  {
    key: 'notifications',
    title: 'Notifications',
    subtitle: 'Notification inbox and read status',
    icon: 'bell',
    listPath: '/notifications',
    clientSearchKeys: ['title', 'message', 'type', 'status'],
    displayFields: ['title', 'message', 'type', 'read', 'created_at'],
    detailFields: ['_id', 'title', 'message', 'type', 'read', 'created_at'],
    rowActions: [
      {
        key: 'read',
        label: 'Mark Read',
        method: 'PATCH',
        path: (record) => `/notifications/${recordId(record)}/read`,
      },
    ],
  },
  {
    key: 'messages',
    title: 'Messages',
    subtitle: 'Private conversation list',
    icon: 'mail',
    listPath: '/messages/conversations',
    createPath: '/messages/conversations',
    clientSearchKeys: ['participant_name', 'last_message', 'type'],
    displayFields: ['type', 'participant_name', 'last_message', 'updated_at'],
    detailFields: ['_id', 'type', 'participants', 'last_message', 'unread_count', 'created_at', 'updated_at'],
    fields: [requiredId('recipient_id', 'Recipient User')],
  },
  {
    key: 'broadcasts',
    title: 'Broadcasts',
    subtitle: 'Admin broadcasts delivered through the messaging backend',
    icon: 'megaphone',
    listPath: '/messages/broadcasts',
    createPath: '/messages/broadcast',
    clientSearchKeys: ['target_group', 'message', 'type'],
    displayFields: ['target_group', 'type', 'message', 'created_at'],
    detailFields: ['_id', 'sender_id', 'target_group', 'type', 'message', 'created_at'],
    fields: [
      { key: 'target_group', label: 'Target Group', type: 'select', required: true, defaultValue: 'all', options: statusOptions('all', 'all_teachers', 'all_students', 'selected') },
      { key: 'type', label: 'Type', type: 'select', defaultValue: 'notice', options: statusOptions('text', 'notice', 'emergency') },
      { key: 'message', label: 'Message', type: 'textarea', required: true },
      { key: 'recipient_ids', label: 'Recipient IDs', type: 'csv', helper: 'Required only for selected target group.' },
    ],
  },
  {
    key: 'schedules',
    title: 'Schedules',
    subtitle: 'Smart schedule and reminder CRUD',
    icon: 'calendar',
    listPath: '/schedules',
    getPath: '/schedules/:id',
    createPath: '/schedules',
    updatePath: '/schedules/:id',
    deletePath: '/schedules/:id',
    filters: [
      { key: 'start', label: 'Start', type: 'text', placeholder: 'YYYY-MM-DD' },
      { key: 'end', label: 'End', type: 'text', placeholder: 'YYYY-MM-DD' },
      { key: 'event_type', label: 'Type', type: 'select', options: [{ label: 'All', value: '' }, ...statusOptions('class', 'exam', 'meeting', 'event', 'reminder', 'deadline', 'personal')] },
      { key: 'status', label: 'Status', type: 'select', options: [{ label: 'All', value: '' }, ...statusOptions('scheduled', 'completed', 'cancelled')] },
    ],
    clientSearchKeys: ['title', 'description', 'event_type', 'location', 'status'],
    displayFields: ['title', 'event_type', 'start_datetime', 'end_datetime', 'priority', 'status'],
    detailFields: ['_id', 'title', 'description', 'start_datetime', 'end_datetime', 'all_day', 'event_type', 'priority', 'color', 'location', 'reminder_type', 'recurring_type', 'assigned_to', 'attachments', 'notes', 'status'],
    fields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'start_datetime', label: 'Start Datetime', required: true, placeholder: '2026-06-20T09:00:00Z' },
      { key: 'end_datetime', label: 'End Datetime', placeholder: '2026-06-20T10:00:00Z' },
      { key: 'all_day', label: 'All Day', type: 'boolean' },
      { key: 'event_type', label: 'Event Type', type: 'select', defaultValue: 'event', options: statusOptions('class', 'exam', 'meeting', 'event', 'reminder', 'deadline', 'personal') },
      { key: 'priority', label: 'Priority', type: 'select', defaultValue: 'medium', options: statusOptions('low', 'medium', 'high', 'urgent') },
      { key: 'color', label: 'Color' },
      { key: 'location', label: 'Location' },
      { key: 'reminder_type', label: 'Reminder Type', type: 'select', defaultValue: 'none', options: statusOptions('none', 'at_time', '5_min', '15_min', '30_min', '1_hour', '1_day') },
      { key: 'recurring_type', label: 'Recurring Type', type: 'select', defaultValue: 'none', options: statusOptions('none', 'daily', 'weekly', 'monthly') },
      { key: 'recurring_end', label: 'Recurring End', type: 'date' },
      { key: 'assigned_to', label: 'Assigned User IDs', type: 'csv' },
      { key: 'attachments', label: 'Attachments', type: 'csv' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    rowActions: [
      {
        key: 'complete',
        label: 'Complete',
        method: 'POST',
        path: (record) => `/schedules/${recordId(record)}/complete`,
      },
    ],
  },
  {
    key: 'settings',
    title: 'Settings',
    subtitle: 'School profile, branding and academic configuration',
    icon: 'settings',
    listPath: '/settings',
    updatePath: '/settings',
    updateMethod: 'PATCH',
    singleton: true,
    displayFields: ['profile.schoolName', 'profile.email', 'profile.phone', 'academic.institutionalLevel'],
    detailFields: [
      'profile.schoolName',
      'profile.email',
      'profile.phone',
      'profile.address',
      'profile.principalName',
      'profile.principalEmail',
      'profile.principalPhone',
      'profile.establishedYear',
      'branding.logoUrl',
      'academic.institutionalLevel',
    ],
    fields: [
      { key: 'profile.schoolName', label: 'School Name' },
      { key: 'profile.email', label: 'School Email', type: 'email' },
      { key: 'profile.phone', label: 'School Phone' },
      { key: 'profile.address', label: 'Address', type: 'textarea' },
      { key: 'profile.principalName', label: 'Principal Name' },
      { key: 'profile.principalEmail', label: 'Principal Email', type: 'email' },
      { key: 'profile.principalPhone', label: 'Principal Phone' },
      { key: 'profile.establishedYear', label: 'Established Year', type: 'number' },
      { key: 'branding.logoUrl', label: 'Logo URL' },
      { key: 'academic.institutionalLevel', label: 'Institutional Level' },
    ],
  },
];

export const ADMIN_MODULE_BY_KEY = ADMIN_MODULES.reduce(
  (acc, module) => {
    acc[module.key] = module;
    return acc;
  },
  {} as Record<string, AdminModuleDefinition>,
);

export const isAdminModuleKey = (value: string): boolean =>
  Object.prototype.hasOwnProperty.call(ADMIN_MODULE_BY_KEY, value);

function recordId(record: AdminRecord): string {
  return String(record._id ?? record.id ?? '');
}
