DROP TABLE IF EXISTS activity_logs;
DROP TABLE IF EXISTS platform_audit_logs;
DROP TABLE IF EXISTS platform_notifications;
DROP TABLE IF EXISTS ticket_messages;
DROP TABLE IF EXISTS support_tickets;
DROP TABLE IF EXISTS school_limits;
DROP TABLE IF EXISTS feature_flags;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS platform_schools;
DROP TABLE IF EXISTS platform_admins;
DROP TABLE IF EXISTS platform_roles;

ALTER TABLE subscriptions DROP COLUMN IF EXISTS cancelled_reason;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS cancelled_at;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS auto_renew;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS features;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS storage_limit_mb;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS teacher_limit;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS trial_ends_at;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS renewal_date;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS expiry_date;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS billing_cycle;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS plan_id;

DROP INDEX IF EXISTS subscription_plans_slug_uniq;
ALTER TABLE subscription_plans DROP COLUMN IF EXISTS sort_order;
ALTER TABLE subscription_plans DROP COLUMN IF EXISTS trial_days;
ALTER TABLE subscription_plans DROP COLUMN IF EXISTS storage_limit_mb;
ALTER TABLE subscription_plans DROP COLUMN IF EXISTS teacher_limit;
ALTER TABLE subscription_plans DROP COLUMN IF EXISTS billing_cycle;
ALTER TABLE subscription_plans DROP COLUMN IF EXISTS description;
ALTER TABLE subscription_plans DROP COLUMN IF EXISTS slug;
